script:
  - docker run --rm -v "$PWD":/gitbook billryan/gitbook gitbook install
  - docker run --rm -v "$PWD":/gitbook billryan/gitbook gitbook build

deploy:
  local_dir: ./_book
  provider: pages:git
  edge: true # opt in to dpl v2
